/// a library of helper functions for code generated by the nodes

// mainly for color, I guess. should write this sometime!

var mainDate = new DateTime(); 

// take 3 floats 0-1 and return an XRRGGBBAA
function rgb2css(r,g,b,a=1) {
	return "x00000000";
}

function hsb2css(h,s,b,a=1) {
	return "x00000000";
}

function glHeader() {
}

function fileWrite(path, content) {}

function fileRead(path) {
	return "";
}

